language: node_js

before_install:
  - npm cache clean
  - npm install

scripts: {
  test: './node_modules/karma/bin/karma start --single-run --browsers PhantomJS',
  gulp: './node_modules/gulp/bin/gulp'
}

node_js:
  - "0.10"

npm:
  - "1.3"

branches:
  only:
    - master